In [13]:
#Data Preprocessing Template
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [14]:
#Encoding Categorical data using LabelEncoder and OneHotEncoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelEncoder_X = LabelEncoder()
categorical_col = labelEncoder_X.fit_transform(X[:,3])
X[:, 3] = categorical_col

ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X), dtype=np.long)

In [15]:
X

array([[     0,      0,      1, 165349, 136897, 471784],
       [     1,      0,      0, 162597, 151377, 443898],
       [     0,      1,      0, 153441, 101145, 407934],
       [     0,      0,      1, 144372, 118671, 383199],
       [     0,      1,      0, 142107,  91391, 366168],
       [     0,      0,      1, 131876,  99814, 362861],
       [     1,      0,      0, 134615, 147198, 127716],
       [     0,      1,      0, 130298, 145530, 323876],
       [     0,      0,      1, 120542, 148718, 311613],
       [     1,      0,      0, 123334, 108679, 304981],
       [     0,      1,      0, 101913, 110594, 229160],
       [     1,      0,      0, 100671,  91790, 249744],
       [     0,      1,      0,  93863, 127320, 249839],
       [     1,      0,      0,  91992, 135495, 252664],
       [     0,      1,      0, 119943, 156547, 256512],
       [     0,      0,      1, 114523, 122616, 261776],
       [     1,      0,      0,  78013, 121597, 264346],
       [     0,      0,      1,

In [17]:
#Avoiding Dummy Variable Trap by reducing one dummy var
X = X[:, 1:]
X

array([[     0,      1, 165349, 136897, 471784],
       [     0,      0, 162597, 151377, 443898],
       [     1,      0, 153441, 101145, 407934],
       [     0,      1, 144372, 118671, 383199],
       [     1,      0, 142107,  91391, 366168],
       [     0,      1, 131876,  99814, 362861],
       [     0,      0, 134615, 147198, 127716],
       [     1,      0, 130298, 145530, 323876],
       [     0,      1, 120542, 148718, 311613],
       [     0,      0, 123334, 108679, 304981],
       [     1,      0, 101913, 110594, 229160],
       [     0,      0, 100671,  91790, 249744],
       [     1,      0,  93863, 127320, 249839],
       [     0,      0,  91992, 135495, 252664],
       [     1,      0, 119943, 156547, 256512],
       [     0,      1, 114523, 122616, 261776],
       [     0,      0,  78013, 121597, 264346],
       [     0,      1,  94657, 145077, 282574],
       [     1,      0,  91749, 114175, 294919],
       [     0,      1,  86419, 153514,      0],
       [     0,     

In [18]:
#Split the data into trainning and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
X_train

array([[     1,      0,  55493, 103057, 214634],
       [     0,      1,  46014,  85047, 205517],
       [     1,      0,  75328, 144135, 134050],
       [     0,      0,  46426, 157693, 210797],
       [     1,      0,  91749, 114175, 294919],
       [     1,      0, 130298, 145530, 323876],
       [     1,      0, 119943, 156547, 256512],
       [     0,      1,   1000, 124153,   1903],
       [     0,      1,    542,  51743,      0],
       [     0,      1,  65605, 153032, 107138],
       [     0,      1, 114523, 122616, 261776],
       [     1,      0,  61994, 115641,  91131],
       [     0,      0,  63408, 129219,  46085],
       [     0,      0,  78013, 121597, 264346],
       [     0,      0,  23640,  96189, 148001],
       [     0,      0,  76253, 113867, 298664],
       [     0,      1,  15505, 127382,  35534],
       [     0,      1, 120542, 148718, 311613],
       [     0,      0,  91992, 135495, 252664],
       [     0,      0,  64664, 139553, 137962],
       [     0,     

In [20]:
y_train

array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
       132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
        97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
       134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
       191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
        90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
       182901.99, 192261.83,  42559.73,  65200.33])

In [21]:
X_test

array([[     1,      0,  66051, 182645, 118148],
       [     0,      0, 100671,  91790, 249744],
       [     1,      0, 101913, 110594, 229160],
       [     1,      0,  27892,  84710, 164470],
       [     1,      0, 153441, 101145, 407934],
       [     0,      1,  72107, 127864, 353183],
       [     0,      1,  20229,  65947, 185265],
       [     0,      1,  61136, 152701,  88218],
       [     1,      0,  73994, 122782, 303319],
       [     1,      0, 142107,  91391, 366168]])

In [22]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [24]:
from sklearn.linear_model import LinearRegression 
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
y_pred = regressor.predict(X_test)

In [27]:
y_pred.astype(int)
y_pred_df = pd.DataFrame(y_pred.astype(int))
y_pred_df

0
0  103015
1  132581
2  132448
3   71975
4  178537
5  116161
6   67851
7   98791
8  113969
9  167921

In [28]:
y_test.astype(int)
y_test_df = pd.DataFrame(y_test.astype(int))
y_test_df

0
0  103282
1  144259
2  146121
3   77798
4  191050
5  105008
6   81229
7   97483
8  110352
9  166187